Repository DOSOPT-CDS-APP-TEAM5/Carrot-Android, pull requests merged in 2023-12, with the labels that each got.

#19 [FEAT/#15] 모임가입하기 / 서버 연결
  app/src/main/java/org/sopt/carrot/data/api/CarrotService.kt
  app/src/main/java/org/sopt/carrot/data/model/join_meeting/JoinMeetingAlbum.kt
  app/src/main/java/org/sopt/carrot/data/model/join_meeting/JoinMeetingData.kt
  app/src/main/java/org/sopt/carrot/data/model/join_meeting/RecyclerData.kt
  app/src/main/java/org/sopt/carrot/data/model/join_meeting/ResponseJoinMeetingDto.kt
  app/src/main/java/org/sopt/carrot/presentation/joinmeeting/JoinMeetingActivity.kt
  app/src/main/java/org/sopt/carrot/presentation/joinmeeting/JoinMeetingAdapter.kt
  app/src/main/java/org/sopt/carrot/presentation/joinmeeting/RecyclerHolder.kt
  app/src/main/res/layout/activity_join_meeting.xml
  app/src/main/res/layout/item_join_meeting.xml
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 📕 현지, ✅ [MOD], ➕ [ADD]

#20 Feature/#18 explore meeting complete
  README.md
  app/src/main/java/org/sopt/carrot/data/api/CarrotService.kt
  app/src/main/java/org/sopt/carrot/data/datasource/remote/ExploreMeetingDataSource.kt
  app/src/main/java/org/sopt/carrot/data/model/BaseResponse.kt
  app/src/main/java/org/sopt/carrot/data/model/Meeting.kt
  app/src/main/java/org/sopt/carrot/data/repo/ExploreMeetingRepository.kt
  app/src/main/java/org/sopt/carrot/presentation/VIewModelFactory.kt
  app/src/main/java/org/sopt/carrot/presentation/exploremeeting/ExploreMeetingActivity.kt
  app/src/main/java/org/sopt/carrot/presentation/exploremeeting/ExploreMeetingViewModel.kt
  app/src/main/java/org/sopt/carrot/presentation/exploremeeting/ScreenMeetingSlideFragment.kt
  app/src/main/java/org/sopt/carrot/presentation/exploremeeting/adapter/MeetingAdapter.kt
  app/src/main/java/org/sopt/carrot/presentation/exploremeeting/viewholder/MeetingViewHolder.kt
  app/src/main/java/org/sopt/carrot/presentation/model/Meeting.kt
  app/src/main/res/drawable/ic_create.xml
  app/src/main/res/drawable/shape_grey200_fill_14_rect.xml
  app/src/main/res/layout/activity_explore_meeting.xml
  app/src/main/res/layout/item_meeting.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: ⭐ [FEAT], 💟 [UI], 🐈‍⬛ 삭, ➕ [ADD]

#22 Feature/#21 동네생활 프로필
  app/src/main/java/org/sopt/carrot/CarrotApp.kt
  app/src/main/java/org/sopt/carrot/data/api/CarrotService.kt
  app/src/main/java/org/sopt/carrot/data/datasource/remote/NeighborhoodLifeRemoteDatasource.kt
  app/src/main/java/org/sopt/carrot/data/datasource/remote/ProfileRemoteDatasource.kt
  app/src/main/java/org/sopt/carrot/data/model/BaseResponse.kt
  app/src/main/java/org/sopt/carrot/data/model/neighborhoodlife/request/ProfileRequest.kt
  app/src/main/java/org/sopt/carrot/data/repo/NeighborhoodLifeRepository.kt
  app/src/main/java/org/sopt/carrot/data/repo/ProfileRepository.kt
  app/src/main/java/org/sopt/carrot/presentation/neighborhoodlife/NeighborhoodLifeFragment.kt
  app/src/main/java/org/sopt/carrot/presentation/neighborhoodlife/NeighborhoodLifeViewModelProvider.kt
  app/src/main/java/org/sopt/carrot/presentation/neighborhoodlife/NeighborhoodViewModel.kt
  app/src/main/java/org/sopt/carrot/presentation/neighborhoodlife/adapter/CarouselTagAdapter.kt
  app/src/main/java/org/sopt/carrot/presentation/neighborhoodlife/adapter/NeighborhoodLifeDivider.kt
  app/src/main/java/org/sopt/carrot/presentation/profile/ProfileActivity.kt
  app/src/main/java/org/sopt/carrot/presentation/profile/ProfileViewModel.kt
  app/src/main/java/org/sopt/carrot/presentation/profile/ProfileViewModelProvider.kt
  app/src/main/java/org/sopt/carrot/presentation/view/CarrotInputLayout.kt
Labels: ⭐ [FEAT], 📗 관희, ➕ [ADD]
