Repository DOSOPT-CDS-APP-TEAM5/Carrot-Android, pull requests merged in 2023-11, with the labels that each got.

#3 Develop/#2 basic set
  .github/ISSUE_TEMPLATE/carrot_issue.md
  .github/pull_request_template.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/carrot/CarrotApp.kt
  app/src/main/java/org/sopt/carrot/core/ui/base/BindingActivity.kt
  app/src/main/java/org/sopt/carrot/core/ui/base/BindingDialogFragment.kt
  app/src/main/java/org/sopt/carrot/core/ui/base/BindingFragment.kt
  app/src/main/java/org/sopt/carrot/core/ui/context/ContextExt.kt
  app/src/main/java/org/sopt/carrot/core/ui/fragment/FragmentExt.kt
  app/src/main/java/org/sopt/carrot/core/ui/view/UiState.kt
  app/src/main/java/org/sopt/carrot/core/ui/view/ViewExt.kt
  app/src/main/java/org/sopt/carrot/data/api/TestService.kt
  app/src/main/java/org/sopt/carrot/data/datasource/TestDataSource.kt
  app/src/main/java/org/sopt/carrot/data/model/TestData.kt
  app/src/main/java/org/sopt/carrot/data/repo/TestRepoImpl.kt
  app/src/main/java/org/sopt/carrot/domain/repo/TestRepository.kt
  app/src/main/java/org/sopt/carrot/presentation/VIewModelFactory.kt
  app/src/main/java/org/sopt/carrot/presentation/test/TestActivity.kt
  app/src/main/java/org/sopt/carrot/presentation/test/TestViewModel.kt
  app/src/main/res/layout/activity_test.xml
  app/src/main/res/values/appearances.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: 🐈‍⬛ 삭, ➕ [ADD]

#4 [ADD] : init color system
  app/src/main/res/values/colors.xml
Labels: 📗 관희, ➕ [ADD]

#16 PR : 동네생활 & 프로필 & 네트워크
  app/build.gradle
  app/src/main/java/org/sopt/carrot/CarrotApp.kt
  app/src/main/java/org/sopt/carrot/core/ui/utils/Extensions.kt
  app/src/main/java/org/sopt/carrot/data/api/CarrotService.kt
  app/src/main/java/org/sopt/carrot/data/api/RetrofitManager.kt
  app/src/main/java/org/sopt/carrot/data/datasource/remote/NeighborhoodLifeRemoteDatasource.kt
  app/src/main/java/org/sopt/carrot/data/model/neighborhoodlife/LivesDataResponse.kt
  app/src/main/java/org/sopt/carrot/data/model/neighborhoodlife/LivesResponse.kt
  app/src/main/java/org/sopt/carrot/data/repo/NeighborhoodLifeRepository.kt
  app/src/main/java/org/sopt/carrot/presentation/VIewModelFactory.kt
  app/src/main/java/org/sopt/carrot/presentation/neighborhoodlife/NeighborhoodLifeFragment.kt
  app/src/main/java/org/sopt/carrot/presentation/neighborhoodlife/NeighborhoodLifeViewModelProvider.kt
  app/src/main/java/org/sopt/carrot/presentation/neighborhoodlife/NeighborhoodViewModel.kt
  app/src/main/java/org/sopt/carrot/presentation/neighborhoodlife/adapter/CarouselTagAdapter.kt
  app/src/main/java/org/sopt/carrot/presentation/neighborhoodlife/adapter/CarouselTextAdapter.kt
  app/src/main/java/org/sopt/carrot/presentation/neighborhoodlife/adapter/NeighborhoodLifeAdapter.kt
  app/src/main/java/org/sopt/carrot/presentation/neighborhoodlife/adapter/NeighborhoodLifeViewHolder.kt
  app/src/main/java/org/sopt/carrot/presentation/neighborhoodlife/dummy/CarouselTag.kt
  app/src/main/java/org/sopt/carrot/presentation/neighborhoodlife/dummy/CarouselText.kt
  app/src/main/java/org/sopt/carrot/presentation/profile/ProfileActivity.kt
  app/src/main/java/org/sopt/carrot/presentation/view/CarrotInputLayout.kt
  app/src/main/res/drawable/ic_alarm.xml
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/ic_comment.xml
  app/src/main/res/drawable/ic_empty_profile.xml
  app/src/main/res/drawable/ic_hamburger.xml
  app/src/main/res/drawable/ic_liked.xml
  app/src/main/res/drawable/ic_navigation_right.xml
  app/src/main/res/drawable/ic_navigation_under.xml
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_searchclub.xml
  app/src/main/res/drawable/sel_profile_button.xml
  app/src/main/res/drawable/shape_grey200_radius_6_rect.xml
  app/src/main/res/drawable/shape_primary_button_radius_6_rect.xml
  app/src/main/res/drawable/shape_stroke_grey100_radius_20_rect.xml
  app/src/main/res/drawable/shape_stroke_grey400_radius_6_rect.xml
  app/src/main/res/drawable/shape_white_circle.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/custom_view_input_text.xml
  app/src/main/res/layout/fragment_neighborhood_life.xml
  app/src/main/res/layout/item_neighborhood_contents.xml
  app/src/main/res/layout/item_neighborhood_meeting.xml
  app/src/main/res/layout/item_topic.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/typhography.xml
Labels: 📗 관희, 💟 [UI], ➕ [ADD]

#14 [UI/#12] 모임가입하기 / UI 구현
  app/src/main/java/org/sopt/carrot/presentation/joinmeeting/JoinMeetingActivity.kt
  app/src/main/res/drawable/chevron_down.xml
  app/src/main/res/drawable/chevron_down_orange.xml
  app/src/main/res/drawable/clock.xml
  app/src/main/res/drawable/ic_alert.xml
  app/src/main/res/drawable/ic_liked_circle.xml
  app/src/main/res/drawable/ic_meatball_circle.xml
  app/src/main/res/drawable/ic_personnel.xml
  app/src/main/res/drawable/ic_share_circle.xml
  app/src/main/res/drawable/join_meeting_button.xml
  app/src/main/res/drawable/join_meeting_grey_background.xml
  app/src/main/res/drawable/join_meeting_look_everything_background.xml
  app/src/main/res/drawable/join_meeting_look_member.xml
  app/src/main/res/drawable/shape_black_fill_rec.xml
  app/src/main/res/layout/activity_join_meeting.xml
  app/src/main/res/layout/item_join_meeting.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 💟 [UI], 📕 현지
